export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const LOGOUT = "LOGOUT";

// portals
export const GET_PORTALS_REQUEST = "GET_PORTALS_REQUEST";
export const GET_PORTALS_SUCCESS = "GET_PORTALS_SUCCESS";
export const GET_PORTALS_FAIL = "GET_PORTALS_FAIL";

export const GET_PORTAL_STATS_REQUEST = "GET_PORTAL_STATS_REQUEST";
export const GET_PORTAL_STATS_SUCCESS = "GET_PORTAL_STATS_SUCCESS";
export const GET_PORTAL_STATS_FAIL = "GET_PORTAL_STATS_FAIL";

export const GET_VIDEOS_REQUEST = "GET_VIDEOS_REQUEST";
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS";
export const GET_VIDEOS_FAIL = "GET_VIDEOS_FAIL";

export const ADD_VIDEO = "ADD_VIDEO";
